### ISSUE TITLE
ImportError: cannot import name 'cache' from 'functools' (/usr/lib/python3.8/functools.py)

### ISSUE THREAD

**Issue by bhcopeland** [kernelci/tuxrun#30]
***In GitLab by @chaws on Jan 26, 2022, 03:08 GMT:***

```bash
$ tuxrun \
      --runtime podman \
      --device qemu-mips64 \
      --kernel https://storage.dev.tuxboot.com/mips64/vmlinux \
      --rootfs https://storage.dev.tuxboot.com/mips64/rootfs.ext4.zst \
      --image docker.io/lavasoftware/lava-dispatcher:2021.11 \
      --tests ltp-fcntl-locktests ltp-fsx ltp-fs_perms_simple ltp-smoke
Traceback (most recent call last):
  File "/home/chaws/.local/bin/tuxrun", line 5, in <module>
    from tuxrun.__main__ import main
  File "/home/chaws/.local/lib/python3.8/site-packages/tuxrun/__main__.py", line 20, in <module>
    from tuxrun import templates
  File "/home/chaws/.local/lib/python3.8/site-packages/tuxrun/templates/__init__.py", line 8, in <module>
    from functools import cache
ImportError: cannot import name 'cache' from 'functools' (/usr/lib/python3.8/functools.py)
```

**Assignees:** ivoire

*Migrated from GitLab: https://gitlab.com/Linaro/tuxrun/-/issues/30*

**Comment by bhcopeland** [comment]
***In GitLab by @ivoire on Jan 27, 2022, 10:11 GMT:***

mentioned in commit 18ee16b1091faf60b2a1a6606ac6fa6ac2bbf661
