### ISSUE TITLE
improve error message handling

### ISSUE THREAD

**Issue by bhcopeland** [kernelci/tuxrun#35]
***In GitLab by @bhcopeland on Mar 1, 2024, 09:17 GMT:***

```
Raised an exception [Errno 2] No such file or directory: 'podman'
Traceback (most recent call last):
  File "/home/ben/.local/share/virtualenvs/Linaro-pZ7OIphy/bin/tuxrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ben/.local/share/virtualenvs/Linaro-pZ7OIphy/lib/python3.11/site-packages/tuxrun/__main__.py", line 478, in main
    return run(options, tmpdir, cache_dir, artefacts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/.local/share/virtualenvs/Linaro-pZ7OIphy/lib/python3.11/site-packages/tuxrun/__main__.py", line 347, in run
    with runtime.run(args):
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/ben/.local/share/virtualenvs/Linaro-pZ7OIphy/lib/python3.11/site-packages/tuxrun/runtimes.py", line 68, in run
    self.__proc__ = subprocess.Popen(
                    ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'podman'
```

If you run tuxrun without podman installed, nothing in tuxrun_reproducer.sh is said and you get a rather unhelpful message

**Assignees:** vishalbhoj, alok.ranjan1

*Migrated from GitLab: https://gitlab.com/Linaro/tuxrun/-/issues/35*

**Comment by bhcopeland** [comment]
***In GitLab by @alok.ranjan1 on Sep 9, 2025, 14:18 GMT+1:***

https://gitlab.com/Linaro/tuxrun/-/merge_requests/415

**Comment by bhcopeland** [comment]
***In GitLab by @alok.ranjan1 on Oct 15, 2025, 11:52 GMT+1:***

set status to **Done**

**Comment by bhcopeland** [comment]
***In GitLab by @alok.ranjan1 on Oct 15, 2025, 11:52 GMT+1:***

This is fixed in tuxrun `v1.3.2` release
